// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `AprilTagsServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __AprilTagsServer_h__
#define __AprilTagsServer_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompAprilTagsServer
{

class AprilTagsServer;
class AprilTagsServerPrx;

}

namespace RoboCompAprilTagsServer
{

struct tag
{
    int id;
    float tx;
    float ty;
    float tz;
    float rx;
    float ry;
    float rz;

    std::tuple<const int&, const float&, const float&, const float&, const float&, const float&, const float&> ice_tuple() const
    {
        return std::tie(id, tx, ty, tz, rx, ry, rz);
    }
};

using tagsList = ::std::vector<::RoboCompAprilTagsServer::tag>;

enum class Mode : unsigned char
{
    YUV422,
    GRAY8,
    RGB888Packet,
    RGB888Planar
};

struct Format
{
    ::RoboCompAprilTagsServer::Mode modeImage;
    int width;
    int height;
    int size;

    std::tuple<const ::RoboCompAprilTagsServer::Mode&, const int&, const int&, const int&> ice_tuple() const
    {
        return std::tie(modeImage, width, height, size);
    }
};

using Frame = ::std::vector<::Ice::Byte>;

struct Image
{
    ::RoboCompAprilTagsServer::Frame data;
    ::RoboCompAprilTagsServer::Format frmt;
    int timeStamp;

    std::tuple<const ::RoboCompAprilTagsServer::Frame&, const ::RoboCompAprilTagsServer::Format&, const int&> ice_tuple() const
    {
        return std::tie(data, frmt, timeStamp);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace RoboCompAprilTagsServer
{

class AprilTagsServer : public virtual ::Ice::Object
{
public:

    using ProxyType = AprilTagsServerPrx;

    virtual bool ice_isA(::std::string, const ::Ice::Current&) const override;
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current&) const override;
    virtual ::std::string ice_id(const ::Ice::Current&) const override;

    static const ::std::string& ice_staticId();

    virtual ::RoboCompAprilTagsServer::tagsList getAprilTags(::RoboCompAprilTagsServer::Image, const ::Ice::Current&) = 0;
    bool _iceD_getAprilTags(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
};

}

namespace RoboCompAprilTagsServer
{

class AprilTagsServerPrx : public virtual ::Ice::Proxy<AprilTagsServerPrx, ::Ice::ObjectPrx>
{
public:

    ::RoboCompAprilTagsServer::tagsList getAprilTags(const ::RoboCompAprilTagsServer::Image& iceP_frame, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::RoboCompAprilTagsServer::tagsList>(true, this, &RoboCompAprilTagsServer::AprilTagsServerPrx::_iceI_getAprilTags, iceP_frame, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getAprilTagsAsync(const ::RoboCompAprilTagsServer::Image& iceP_frame, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<::RoboCompAprilTagsServer::tagsList>>().get_future())
    {
        return _makePromiseOutgoing<::RoboCompAprilTagsServer::tagsList, P>(false, this, &RoboCompAprilTagsServer::AprilTagsServerPrx::_iceI_getAprilTags, iceP_frame, context);
    }

    ::std::function<void()>
    getAprilTagsAsync(const ::RoboCompAprilTagsServer::Image& iceP_frame,
                      ::std::function<void(::RoboCompAprilTagsServer::tagsList)> response,
                      ::std::function<void(::std::exception_ptr)> ex = nullptr,
                      ::std::function<void(bool)> sent = nullptr,
                      const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::RoboCompAprilTagsServer::tagsList>(response, ex, sent, this, &RoboCompAprilTagsServer::AprilTagsServerPrx::_iceI_getAprilTags, iceP_frame, context);
    }

    void _iceI_getAprilTags(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompAprilTagsServer::tagsList>>&, const ::RoboCompAprilTagsServer::Image&, const ::Ice::Context&);

    static const ::std::string& ice_staticId();

protected:

    AprilTagsServerPrx() = default;
    friend ::std::shared_ptr<AprilTagsServerPrx> IceInternal::createProxy<AprilTagsServerPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
};

}

namespace Ice
{

template<>
struct StreamableTraits<::RoboCompAprilTagsServer::tag>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 28;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamReader<::RoboCompAprilTagsServer::tag, S>
{
    static void read(S* istr, ::RoboCompAprilTagsServer::tag& v)
    {
        istr->readAll(v.id, v.tx, v.ty, v.tz, v.rx, v.ry, v.rz);
    }
};

template<>
struct StreamableTraits< ::RoboCompAprilTagsServer::Mode>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 3;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<>
struct StreamableTraits<::RoboCompAprilTagsServer::Format>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 13;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::RoboCompAprilTagsServer::Format, S>
{
    static void read(S* istr, ::RoboCompAprilTagsServer::Format& v)
    {
        istr->readAll(v.modeImage, v.width, v.height, v.size);
    }
};

template<>
struct StreamableTraits<::RoboCompAprilTagsServer::Image>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 18;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::RoboCompAprilTagsServer::Image, S>
{
    static void read(S* istr, ::RoboCompAprilTagsServer::Image& v)
    {
        istr->readAll(v.data, v.frmt, v.timeStamp);
    }
};

}

namespace RoboCompAprilTagsServer
{

using AprilTagsServerPtr = ::std::shared_ptr<AprilTagsServer>;
using AprilTagsServerPrxPtr = ::std::shared_ptr<AprilTagsServerPrx>;

}

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompAprilTagsServer
{

class AprilTagsServer;
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompAprilTagsServer::AprilTagsServer>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompAprilTagsServer::AprilTagsServer*);

}

}

namespace RoboCompAprilTagsServer
{

class AprilTagsServer;
::Ice::Object* upCast(::RoboCompAprilTagsServer::AprilTagsServer*);
typedef ::IceInternal::Handle< ::RoboCompAprilTagsServer::AprilTagsServer> AprilTagsServerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompAprilTagsServer::AprilTagsServer> AprilTagsServerPrx;
typedef AprilTagsServerPrx AprilTagsServerPrxPtr;
void _icePatchObjectPtr(AprilTagsServerPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompAprilTagsServer
{

struct tag
{
    ::Ice::Int id;
    ::Ice::Float tx;
    ::Ice::Float ty;
    ::Ice::Float tz;
    ::Ice::Float rx;
    ::Ice::Float ry;
    ::Ice::Float rz;
};

typedef ::std::vector< ::RoboCompAprilTagsServer::tag> tagsList;

enum Mode
{
    YUV422,
    GRAY8,
    RGB888Packet,
    RGB888Planar
};

struct Format
{
    ::RoboCompAprilTagsServer::Mode modeImage;
    ::Ice::Int width;
    ::Ice::Int height;
    ::Ice::Int size;

    bool operator==(const Format& rhs_) const
    {
        if(this == &rhs_)
        {
            return true;
        }
        if(modeImage != rhs_.modeImage)
        {
            return false;
        }
        if(width != rhs_.width)
        {
            return false;
        }
        if(height != rhs_.height)
        {
            return false;
        }
        if(size != rhs_.size)
        {
            return false;
        }
        return true;
    }

    bool operator<(const Format& rhs_) const
    {
        if(this == &rhs_)
        {
            return false;
        }
        if(modeImage < rhs_.modeImage)
        {
            return true;
        }
        else if(rhs_.modeImage < modeImage)
        {
            return false;
        }
        if(width < rhs_.width)
        {
            return true;
        }
        else if(rhs_.width < width)
        {
            return false;
        }
        if(height < rhs_.height)
        {
            return true;
        }
        else if(rhs_.height < height)
        {
            return false;
        }
        if(size < rhs_.size)
        {
            return true;
        }
        else if(rhs_.size < size)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const Format& rhs_) const
    {
        return !operator==(rhs_);
    }
    bool operator<=(const Format& rhs_) const
    {
        return operator<(rhs_) || operator==(rhs_);
    }
    bool operator>(const Format& rhs_) const
    {
        return !operator<(rhs_) && !operator==(rhs_);
    }
    bool operator>=(const Format& rhs_) const
    {
        return !operator<(rhs_);
    }
};

typedef ::std::vector< ::Ice::Byte> Frame;

struct Image
{
    ::RoboCompAprilTagsServer::Frame data;
    ::RoboCompAprilTagsServer::Format frmt;
    ::Ice::Int timeStamp;
};

}

namespace RoboCompAprilTagsServer
{

class Callback_AprilTagsServer_getAprilTags_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AprilTagsServer_getAprilTags_Base> Callback_AprilTagsServer_getAprilTagsPtr;

}

namespace IceProxy
{

namespace RoboCompAprilTagsServer
{

class AprilTagsServer : public virtual ::Ice::Proxy<AprilTagsServer, ::IceProxy::Ice::Object>
{
public:

    ::RoboCompAprilTagsServer::tagsList getAprilTags(const ::RoboCompAprilTagsServer::Image& iceP_frame, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_getAprilTags(_iceI_begin_getAprilTags(iceP_frame, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getAprilTags(const ::RoboCompAprilTagsServer::Image& iceP_frame, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getAprilTags(iceP_frame, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getAprilTags(const ::RoboCompAprilTagsServer::Image& iceP_frame, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getAprilTags(iceP_frame, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getAprilTags(const ::RoboCompAprilTagsServer::Image& iceP_frame, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getAprilTags(iceP_frame, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getAprilTags(const ::RoboCompAprilTagsServer::Image& iceP_frame, const ::RoboCompAprilTagsServer::Callback_AprilTagsServer_getAprilTagsPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getAprilTags(iceP_frame, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_getAprilTags(const ::RoboCompAprilTagsServer::Image& iceP_frame, const ::Ice::Context& context, const ::RoboCompAprilTagsServer::Callback_AprilTagsServer_getAprilTagsPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getAprilTags(iceP_frame, context, del, cookie);
    }

    ::RoboCompAprilTagsServer::tagsList end_getAprilTags(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getAprilTags(const ::RoboCompAprilTagsServer::Image&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    static const ::std::string& ice_staticId();

protected:

    virtual ::IceProxy::Ice::Object* _newInstance() const;
};

}

}

namespace RoboCompAprilTagsServer
{

class AprilTagsServer : public virtual ::Ice::Object
{
public:

    typedef AprilTagsServerPrx ProxyType;
    typedef AprilTagsServerPtr PointerType;

    virtual ~AprilTagsServer();

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::emptyCurrent) const;

    static const ::std::string& ice_staticId();

    virtual ::RoboCompAprilTagsServer::tagsList getAprilTags(const ::RoboCompAprilTagsServer::Image&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_getAprilTags(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:

    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
};

inline bool operator==(const AprilTagsServer& lhs, const AprilTagsServer& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const AprilTagsServer& lhs, const AprilTagsServer& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}

}

namespace Ice
{

template<>
struct StreamableTraits< ::RoboCompAprilTagsServer::tag>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 28;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamWriter< ::RoboCompAprilTagsServer::tag, S>
{
    static void write(S* ostr, const ::RoboCompAprilTagsServer::tag& v)
    {
        ostr->write(v.id);
        ostr->write(v.tx);
        ostr->write(v.ty);
        ostr->write(v.tz);
        ostr->write(v.rx);
        ostr->write(v.ry);
        ostr->write(v.rz);
    }
};

template<typename S>
struct StreamReader< ::RoboCompAprilTagsServer::tag, S>
{
    static void read(S* istr, ::RoboCompAprilTagsServer::tag& v)
    {
        istr->read(v.id);
        istr->read(v.tx);
        istr->read(v.ty);
        istr->read(v.tz);
        istr->read(v.rx);
        istr->read(v.ry);
        istr->read(v.rz);
    }
};

template<>
struct StreamableTraits< ::RoboCompAprilTagsServer::Mode>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 3;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<>
struct StreamableTraits< ::RoboCompAprilTagsServer::Format>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 13;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::RoboCompAprilTagsServer::Format, S>
{
    static void write(S* ostr, const ::RoboCompAprilTagsServer::Format& v)
    {
        ostr->write(v.modeImage);
        ostr->write(v.width);
        ostr->write(v.height);
        ostr->write(v.size);
    }
};

template<typename S>
struct StreamReader< ::RoboCompAprilTagsServer::Format, S>
{
    static void read(S* istr, ::RoboCompAprilTagsServer::Format& v)
    {
        istr->read(v.modeImage);
        istr->read(v.width);
        istr->read(v.height);
        istr->read(v.size);
    }
};

template<>
struct StreamableTraits< ::RoboCompAprilTagsServer::Image>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 18;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::RoboCompAprilTagsServer::Image, S>
{
    static void write(S* ostr, const ::RoboCompAprilTagsServer::Image& v)
    {
        ostr->write(v.data);
        ostr->write(v.frmt);
        ostr->write(v.timeStamp);
    }
};

template<typename S>
struct StreamReader< ::RoboCompAprilTagsServer::Image, S>
{
    static void read(S* istr, ::RoboCompAprilTagsServer::Image& v)
    {
        istr->read(v.data);
        istr->read(v.frmt);
        istr->read(v.timeStamp);
    }
};

}

namespace RoboCompAprilTagsServer
{

template<class T>
class CallbackNC_AprilTagsServer_getAprilTags : public Callback_AprilTagsServer_getAprilTags_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::RoboCompAprilTagsServer::tagsList&);

    CallbackNC_AprilTagsServer_getAprilTags(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompAprilTagsServer::AprilTagsServerPrx proxy = ::RoboCompAprilTagsServer::AprilTagsServerPrx::uncheckedCast(result->getProxy());
        ::RoboCompAprilTagsServer::tagsList ret;
        try
        {
            ret = proxy->end_getAprilTags(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }

private:

    Response _response;
};

template<class T> Callback_AprilTagsServer_getAprilTagsPtr
newCallback_AprilTagsServer_getAprilTags(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::RoboCompAprilTagsServer::tagsList&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AprilTagsServer_getAprilTags<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AprilTagsServer_getAprilTagsPtr
newCallback_AprilTagsServer_getAprilTags(T* instance, void (T::*cb)(const ::RoboCompAprilTagsServer::tagsList&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AprilTagsServer_getAprilTags<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_AprilTagsServer_getAprilTags : public Callback_AprilTagsServer_getAprilTags_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::RoboCompAprilTagsServer::tagsList&, const CT&);

    Callback_AprilTagsServer_getAprilTags(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ::RoboCompAprilTagsServer::AprilTagsServerPrx proxy = ::RoboCompAprilTagsServer::AprilTagsServerPrx::uncheckedCast(result->getProxy());
        ::RoboCompAprilTagsServer::tagsList ret;
        try
        {
            ret = proxy->end_getAprilTags(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }

private:

    Response _response;
};

template<class T, typename CT> Callback_AprilTagsServer_getAprilTagsPtr
newCallback_AprilTagsServer_getAprilTags(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::RoboCompAprilTagsServer::tagsList&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AprilTagsServer_getAprilTags<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AprilTagsServer_getAprilTagsPtr
newCallback_AprilTagsServer_getAprilTags(T* instance, void (T::*cb)(const ::RoboCompAprilTagsServer::tagsList&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AprilTagsServer_getAprilTags<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
