
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AGM2AGENT AGM2AGENTICE AGM2AGENTROS AGMAGENT CBRACE COMMA COMMUNICATIONS COMPONENT CPAR CPP CPP11 GUI ICE IDENTIFIER IMPLEMENTS IMPORT INNERMODELVIEWER LANGUAGE OBRACE OPAR OPTIONS PATH PUBLISHES PYTHON QDIALOG QMAINWINDOW QT QUOTE QWIDGET REQUIRES ROS SEMI STATEMACHINE SUBSCRIBESTO VISUALcomponent : importslist COMPONENT IDENTIFIER OBRACE content CBRACE SEMI\n    importslist  : idslimport importslist\n                 |\n    \n    idslimport  : IMPORT QUOTE PATH QUOTE SEMI\n    content  : commblock language otherslistlanguage\t: LANGUAGE langopts SEMI\n    langopts    : CPP\n                | CPP11\n                | PYTHON\n    \n    otherslist  : otherslist others\n                |\n    \n    others  : gui\n            | statemachine\n            | options\n    \n    gui\t\t: GUI QT OPAR guiopts CPAR SEMI\n    \n    guiopts\t: QWIDGET\n            | QMAINWINDOW\n            | QDIALOG\n    \n    options : OPTIONS optionsoptlist SEMI\n    \n    optionsoptlist  : optionsoptlist COMMA optionsopt\n                    | optionsopt\n    \n    optionsopt\t: INNERMODELVIEWER\n                | AGMAGENT\n                | AGM2AGENT\n                | AGM2AGENTICE\n                | AGM2AGENTROS\n    \n    statemachine    : STATEMACHINE QUOTE PATH QUOTE stmvisual SEMI\n    \n    stmvisual   : VISUAL\n                |\n    commblock\t: COMMUNICATIONS OBRACE commlist CBRACE SEMIcommlist : commlist comm\n                | comm : commkeywords commalist SEMIcommkeywords : IMPLEMENTS\n                    | REQUIRES\n\t\t            | SUBSCRIBESTO\n\t\t            | PUBLISHEScommalist    : commalist COMMA commitem\n                    | commitem\n    commitem    : IDENTIFIER commtype\n                | IDENTIFIER\n    commtype : OPAR ICE CPAR\n                | OPAR ROS CPAR\n    '
    
_lr_action_items = {'COMPONENT':([0,2,3,6,15,],[-3,5,-3,-2,-4,]),'IMPORT':([0,3,15,],[4,4,-4,]),'$end':([1,20,],[0,-1,]),'QUOTE':([4,9,32,56,],[7,11,43,67,]),'IDENTIFIER':([5,37,38,39,40,41,60,],[8,54,-34,-35,-36,-37,54,]),'PATH':([7,43,],[9,56,]),'OBRACE':([8,14,],[10,19,]),'COMMUNICATIONS':([10,],[14,]),'SEMI':([11,16,22,23,24,25,35,44,45,46,47,48,49,50,52,53,54,61,67,68,69,72,73,74,75,76,],[15,20,34,-7,-8,-9,51,57,-21,-22,-23,-24,-25,-26,59,-39,-41,-40,-29,-20,-38,77,78,-28,-42,-43,]),'CBRACE':([12,17,19,21,26,27,28,29,30,34,36,57,59,77,78,],[16,-11,-32,-5,35,-10,-12,-13,-14,-6,-31,-19,-33,-15,-27,]),'LANGUAGE':([13,51,],[18,-30,]),'GUI':([17,21,27,28,29,30,34,57,77,78,],[-11,31,-10,-12,-13,-14,-6,-19,-15,-27,]),'STATEMACHINE':([17,21,27,28,29,30,34,57,77,78,],[-11,32,-10,-12,-13,-14,-6,-19,-15,-27,]),'OPTIONS':([17,21,27,28,29,30,34,57,77,78,],[-11,33,-10,-12,-13,-14,-6,-19,-15,-27,]),'CPP':([18,],[23,]),'CPP11':([18,],[24,]),'PYTHON':([18,],[25,]),'IMPLEMENTS':([19,26,36,59,],[-32,38,-31,-33,]),'REQUIRES':([19,26,36,59,],[-32,39,-31,-33,]),'SUBSCRIBESTO':([19,26,36,59,],[-32,40,-31,-33,]),'PUBLISHES':([19,26,36,59,],[-32,41,-31,-33,]),'QT':([31,],[42,]),'INNERMODELVIEWER':([33,58,],[46,46,]),'AGMAGENT':([33,58,],[47,47,]),'AGM2AGENT':([33,58,],[48,48,]),'AGM2AGENTICE':([33,58,],[49,49,]),'AGM2AGENTROS':([33,58,],[50,50,]),'OPAR':([42,54,],[55,62,]),'COMMA':([44,45,46,47,48,49,50,52,53,54,61,68,69,75,76,],[58,-21,-22,-23,-24,-25,-26,60,-39,-41,-40,-20,-38,-42,-43,]),'QWIDGET':([55,],[64,]),'QMAINWINDOW':([55,],[65,]),'QDIALOG':([55,],[66,]),'ICE':([62,],[70,]),'ROS':([62,],[71,]),'CPAR':([63,64,65,66,70,71,],[72,-16,-17,-18,75,76,]),'VISUAL':([67,],[74,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'component':([0,],[1,]),'importslist':([0,3,],[2,6,]),'idslimport':([0,3,],[3,3,]),'content':([10,],[12,]),'commblock':([10,],[13,]),'language':([13,],[17,]),'otherslist':([17,],[21,]),'langopts':([18,],[22,]),'commlist':([19,],[26,]),'others':([21,],[27,]),'gui':([21,],[28,]),'statemachine':([21,],[29,]),'options':([21,],[30,]),'comm':([26,],[36,]),'commkeywords':([26,],[37,]),'optionsoptlist':([33,],[44,]),'optionsopt':([33,58,],[45,68,]),'commalist':([37,],[52,]),'commitem':([37,60,],[53,69,]),'commtype':([54,],[61,]),'guiopts':([55,],[63,]),'stmvisual':([67,],[73,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> component","S'",1,None,None,None),
  ('component -> importslist COMPONENT IDENTIFIER OBRACE content CBRACE SEMI','component',7,'p_component','ply-test.py',185),
  ('importslist -> idslimport importslist','importslist',2,'p_importslist','ply-test.py',191),
  ('importslist -> <empty>','importslist',0,'p_importslist','ply-test.py',192),
  ('idslimport -> IMPORT QUOTE PATH QUOTE SEMI','idslimport',5,'p_idslimport','ply-test.py',204),
  ('content -> commblock language otherslist','content',3,'p_content','ply-test.py',212),
  ('language -> LANGUAGE langopts SEMI','language',3,'p_language','ply-test.py',219),
  ('langopts -> CPP','langopts',1,'p_langopts','ply-test.py',224),
  ('langopts -> CPP11','langopts',1,'p_langopts','ply-test.py',225),
  ('langopts -> PYTHON','langopts',1,'p_langopts','ply-test.py',226),
  ('otherslist -> otherslist others','otherslist',2,'p_otherslist','ply-test.py',232),
  ('otherslist -> <empty>','otherslist',0,'p_otherslist','ply-test.py',233),
  ('others -> gui','others',1,'p_others','ply-test.py',245),
  ('others -> statemachine','others',1,'p_others','ply-test.py',246),
  ('others -> options','others',1,'p_others','ply-test.py',247),
  ('gui -> GUI QT OPAR guiopts CPAR SEMI','gui',6,'p_gui','ply-test.py',253),
  ('guiopts -> QWIDGET','guiopts',1,'p_guiopts','ply-test.py',262),
  ('guiopts -> QMAINWINDOW','guiopts',1,'p_guiopts','ply-test.py',263),
  ('guiopts -> QDIALOG','guiopts',1,'p_guiopts','ply-test.py',264),
  ('options -> OPTIONS optionsoptlist SEMI','options',3,'p_options','ply-test.py',270),
  ('optionsoptlist -> optionsoptlist COMMA optionsopt','optionsoptlist',3,'p_optionsoptlist','ply-test.py',279),
  ('optionsoptlist -> optionsopt','optionsoptlist',1,'p_optionsoptlist','ply-test.py',280),
  ('optionsopt -> INNERMODELVIEWER','optionsopt',1,'p_optionsopt','ply-test.py',292),
  ('optionsopt -> AGMAGENT','optionsopt',1,'p_optionsopt','ply-test.py',293),
  ('optionsopt -> AGM2AGENT','optionsopt',1,'p_optionsopt','ply-test.py',294),
  ('optionsopt -> AGM2AGENTICE','optionsopt',1,'p_optionsopt','ply-test.py',295),
  ('optionsopt -> AGM2AGENTROS','optionsopt',1,'p_optionsopt','ply-test.py',296),
  ('statemachine -> STATEMACHINE QUOTE PATH QUOTE stmvisual SEMI','statemachine',6,'p_statemachine','ply-test.py',302),
  ('stmvisual -> VISUAL','stmvisual',1,'p_stmvisual','ply-test.py',311),
  ('stmvisual -> <empty>','stmvisual',0,'p_stmvisual','ply-test.py',312),
  ('commblock -> COMMUNICATIONS OBRACE commlist CBRACE SEMI','commblock',5,'p_commblock','ply-test.py',321),
  ('commlist -> commlist comm','commlist',2,'p_commlist','ply-test.py',325),
  ('commlist -> <empty>','commlist',0,'p_commlist','ply-test.py',326),
  ('comm -> commkeywords commalist SEMI','comm',3,'p_comm','ply-test.py',340),
  ('commkeywords -> IMPLEMENTS','commkeywords',1,'p_commkeywords','ply-test.py',345),
  ('commkeywords -> REQUIRES','commkeywords',1,'p_commkeywords','ply-test.py',346),
  ('commkeywords -> SUBSCRIBESTO','commkeywords',1,'p_commkeywords','ply-test.py',347),
  ('commkeywords -> PUBLISHES','commkeywords',1,'p_commkeywords','ply-test.py',348),
  ('commalist -> commalist COMMA commitem','commalist',3,'p_commalist','ply-test.py',352),
  ('commalist -> commitem','commalist',1,'p_commalist','ply-test.py',353),
  ('commitem -> IDENTIFIER commtype','commitem',2,'p_commitem','ply-test.py',363),
  ('commitem -> IDENTIFIER','commitem',1,'p_commitem','ply-test.py',364),
  ('commtype -> OPAR ICE CPAR','commtype',3,'p_commtype','ply-test.py',374),
  ('commtype -> OPAR ROS CPAR','commtype',3,'p_commtype','ply-test.py',375),
]
